name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: [RelWithDebInfo]
        ui: [gui]
        scripting: [lua]
    
    steps:
      # 修复点1：统一步骤缩进为2空格
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      
      - name: Install Skia
        if: ${{ matrix.ui == 'gui' }}
        shell: bash
        run: |
          WORKSPACE_PATH="${GITHUB_WORKSPACE//\\//}"
          skia_url=$(source "$WORKSPACE_PATH/laf/misc/skia-url.sh")
          curl --retry 3 -L -o skia.zip "$skia_url"
          unzip -q skia.zip -d skia
      
      - uses: aseprite/get-ninja@main
      - uses: ilammy/msvc-dev-cmd@v1
      
      - name: Generating Makefiles
        shell: bash
        run: |
          cmake -S . -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -DENABLE_SCRIPTING=ON \
            -DLAF_BACKEND=skia \
            -DSKIA_DIR="$PWD/skia" \
            -DSKIA_LIBRARY_DIR="$PWD/skia/out/Release-x64"
      
      - name: Compiling
        shell: bash
        run: cd build && ninja
      
      - name: Package Release
        shell: powershell
        run: |
          # 动态定位 ver.h 文件（优先检查构建目录）
          $verPath = if (Test-Path "build\src\ver.h") { 
            "build\src\ver.h" 
          } else { 
            "src\ver.h"
          }
          #  若仍不存在则强制报错退出
          if (-not (Test-Path $verPath)) {
            Write-Error "❌ 致命错误：未找到版本文件 ver.h"
            exit 1
          }
          # 安全读取版本号（修正引号问题）
          $verLine = Get-Content $verPath | Select-String '#define VERSION'
          $version = $verLine.Line.Split()[-1].Trim('"')  # 关键修复
          # 打包操作
          $pkgDir = "aseprite-$version-windows"
          New-Item -Type Directory -Path $pkgDir -Force
          Copy-Item "build\bin\*" $pkgDir
          Compress-Archive -Path $pkgDir -DestinationPath "$pkgDir.zip"
          # 导出路径供后续上传使用
          echo "PACKAGE_PATH=$pwd\$pkgDir.zip" >> $env:GITHUB_ENV
      
      # 修复点2：上传步骤独立于Package Release
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: aseprite-build
          path: ${{ env.PACKAGE_PATH }}
